Refactor monitor_repo function for improved error handling and readability; update package list generation and release file creation process.

diff --git a/mkaptrepo b/mkaptrepo
--- a/mkaptrepo
+++ b/mkaptrepo
@@ -17,45 +17,35 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 function monitor_repo() {
-    inotifywait -m -e create,delete,modify,move "$_repoPath/pool" | while read -r directory events filename; do
-        echo "Detected changes in $directory: $events on $filename"
-        dpkg-scanpackages --arch amd64 "$_repoPath"/pool > $_packageList
 
-        # Remove `$_repoPath` from filename entry
-        sed -i "s|$_repoPath/||g" "$_packageList"
+    cd "$_repoPath/$_repositoryName" || { echo "$_repoPath/$_repositoryName does not exist." >&2 ; exit 1 ; }
+
+    local pwdDir packageList
+
+    pwdDir="$(pwd)"
+    packageList="$_packageList"
+
+
+    inotifywait -m -e create,delete,modify,move -r ./pool | while read -r directory events filename; do
+        echo "Detected changes in $directory: $events on $filename"
+
+        # shellcheck disable=SC2086
+        dpkg-scanpackages --arch amd64 ./pool > ${packageList} || {
+            echo "dpkg-scanpackages failed, please check your package files." >&2
+            exit 1
+        }
+
+        # Remove `./` prefix from the package list
+        sed -i "s|^\./||g" "$_packageList"
 
         gzip -k -f "$_packageList"
         xz -k -f "$_packageList"
 
-        rm -vf "$_release.gpg" "$_inrelease"
+        gen_release || { echo "Generating Release file failed!" >&2 ; exit 1 ; }
+        git_commit || { echo "git commit failed!" >&2 ; exit 1 ; }
 
-        echo "$_releaseFile" > "$_release"
+        cd "$pwdDir" || exit 1
 
-        cd "$_distPath/stable" || exit 1
-
-        # for some reason the following doesn't work:
-        # {
-        #     do_hash "MD5Sum" "md5sum"
-        #     do_hash "SHA1" "sha1sum"
-        #     do_hash "SHA256" "sha256sum"
-        # } >> Release
-
-        # shellcheck disable=SC2129
-        do_hash "MD5Sum" "md5sum" >> Release
-        do_hash "SHA1" "sha1sum" >> Release
-        do_hash "SHA256" "sha256sum" >> Release
-
-        cd "$_repoPath" || exit 1
-
-        gpg --default-key HowToNebie -abs -o $_release.gpg $_release
-        gpg --default-key HowToNebie --clearsign -o $_inrelease $_release
-
-        if git_commit ; then
-            git push origin main || {
-                echo "git push failed, please check your network connection and try again." >&2
-                exit 1
-            }
-        fi
     done
 }
 
@@ -77,7 +67,7 @@ function do_hash () {
 
     done
 
-    sed -i "s|$_repoPath/||g" "$_release"
+    sed -i "s|$_repoPath/||g" Release
 }
 
 function git_commit() {
@@ -88,7 +78,7 @@ function git_commit() {
 
     # Generate a commit message based on what has changed use `git status`
     # to get the list of changed files
-    for status in modified deleted created renamed; do
+    for status in R M A C D; do
         git status --porcelain | grep "^${status}" | while read -r line; do
             file=$(echo "$line" | cut -c4-)
             commitMessage="Update ${file} with package details and description"
@@ -99,6 +89,28 @@ function git_commit() {
         echo "git commit failed, no changes to commit." >&2
         return 1
     }
+
+    git push origin main || { echo "git push failed!" >&2 ; exit 1 ; }
+}
+
+function gen_release () {
+
+        cd "dists/stable" || exit 1
+
+        rm -fv Release Release.gpg InRelease
+
+        echo "$_releaseFile" > Release
+
+        for algo in "MD5Sum md5sum" "SHA1 sha1sum" "SHA256 sha256sum"; do
+            read -r hashName hashCmd <<< "$algo"
+            do_hash "$hashName" "$hashCmd" >> Release
+        done >> Release
+
+        gpg --default-key HowToNebie -abs -o Release.gpg Release
+        gpg --default-key HowToNebie --clearsign -o InRelease Release
+
+        test "$?" -eq "0" || { echo "Singing the Release file failed!" >&2 ; exit 1 ; }
+
 }
 
 set -eo pipefail
@@ -121,25 +133,25 @@ _codename="${CODENAME:-stable}"
 _architectures="${ARCHITECTURES:-$(dpkg --print-architecture)}"
 _components="${COMPONENTS:-main}"
 _maintainer="${MAINTAINER:-$(git config user.name) <$(git config user.email)>}"
+_repoPath="${REPO_PATH:-not set}"
 
 _distPath="$_repoPath/dists"
 
-_release="$_distPath/stable/Release"
+_release="dists/stable/Release"
 _inrelease="$_distPath/stable/InRelease"
-_packageList="$_distPath/stable/main/binary-amd64/Packages"
+_packageList="dists/stable/main/binary-amd64/Packages"
 
 _releaseFile="$(cat <<EOF
-Origin: HowToNebie
-Label: default
-Suite: stable
-Codename: stable
+Origin: $_origin/$_repositoryName
+Label: $_label
+Suite: $_suite
+Codename: $_codename
 Version: 1.0
-Architectures: amd64
-Components: main
-Description: HowToNubie.com APT Repository
- APT repository for HowToNubie.com
-Maintainer: Michael L. Schaecher <MichaelLeeSchaecher.com>
-date: $(date -Ru)
+Architectures: $_architectures
+Components: $_components
+Description: Publicly available APT repository for $_origin
+Maintainer: $_maintainer
+Date: $(date -Ru)
 EOF
 )"
 
